title: "Darren's Blog"
author: "Darren Ou"
description: "Really cool blog about ... something"
lang: "en"
url: "https://oudushu.github.io"

# Page settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/
#paginate: 8                 # use "layout: paginate" in the index.html to enable pagination

# Theme settings
hide_title: true            # remove site heading in the header
hide_footer: true           # hide the "previous" and "next" links at the end of each post
dark_theme: false            # use the dark mode as default
dark_header: true           # keep the header dark
dark_footer: false           # keep the footer dark
# style: minimal             # use a simpler style inspired by the minima theme

weibo_username:     欧杜书
# zhihu_username:     huxpro
github_username:    OuDuShu
email:  sysbox2019@gmail.com

navigation:                  # site navigation in the header
  - index.html
  - README.md
#  - title: "https://"       # linking external sites is also supported

#icons:                      # icons in the header, see http://fontawesome.com/icons
#  envelope: "mailto:niklasbuschmann@users.noreply.github.com"
github: "https://github.com/OuDuShu"
#  rss: "/contrast/feed.xml"

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

plugins: 
 - jekyll-feed
 - jekyll-paginate
 - jekyll-default-layout
